apiVersion: apps/v1
kind: Deployment
metadata:
  name: finguard-deployment
  labels:
    app: finguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finguard
  template:
    metadata:
      labels:
        app: finguard
    spec:
      containers:
      - name: finguard
        image: fafiorim/finguard:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 3443
          name: https
        env:
        - name: ADMIN_USERNAME
          valueFrom:
            configMapKeyRef:
              name: finguard-config
              key: admin-username
        - name: USER_USERNAME
          valueFrom:
            configMapKeyRef:
              name: finguard-config
              key: user-username
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: finguard-secrets
              key: admin-password
        - name: USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: finguard-secrets
              key: user-password
        - name: FSS_API_KEY
          valueFrom:
            secretKeyRef:
              name: finguard-secrets
              key: fss-api-key
        volumeMounts:
        - name: uploads-volume
          mountPath: /app/uploads
      volumes:
      - name: uploads-volume
        emptyDir: {}
