apiVersion: v1
kind: Secret
metadata:
  name: finguard-secrets
  labels:
    app: finguard
type: Opaque
stringData:
  admin-password: "changeMe123"
  user-password: "userPass123"
  fss-api-key: "REPLACE_WITH_YOUR_FSS_API_KEY"
