apiVersion: v1
kind: Service
metadata:
  name: finguard-service
  labels:
    app: finguard
spec:
  selector:
    app: finguard
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
